name: Handle move

on:
  repository_dispatch:
    types: [make_move]


jobs:
  handle-move:
    runs-on: self-hosted
    permissions:
      contents: write
    container:
      image: ghcr.io/aragornofkebroyd/github-chess/chess-env:latest

    steps:
      - uses: actions/checkout@v4

      - name: Process move
        run: |
          echo "Move payload: ${{ github.event.client_payload }}"
          python scripts/update_board.py "${{ github.event.client_payload.game }}" "${{ github.event.client_payload.move }}"
      

      - name: Commit updated board and README
        working-directory: ${{ github.workspace }}
        run: |
          git config --global --add safe.directory /__w/Github-Chess/Github-Chess
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add state.json README.md
          git commit -m "Apply move ${{ github.event.client_payload.move }}" || echo "No changes"
          git pull
          git rebase
          git push